name: Split

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  split_monorepo:
    needs: provide_packages_json

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

    steps:
      -   uses: actions/checkout@v2

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Split of ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@2.0
        env:
          GITHUB_TOKEN: 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
        with:
          package-directory: 'Modules/${{ matrix.package }}'
          split-repository-organization: 'snlprjti'
          split-repository-name: '${{ matrix.package }}'
          user-name: "snlprjti"
          user-email: "snlprjpti@gmail.com"
          branch: "main"

      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        # Uses an action in the root directory
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: symplify/github-action-monorepo-split@2.0
        env:
          GITHUB_TOKEN: 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
        with:
          tag: ${GITHUB_REF#refs/tags/}

          package-directory: 'Modules/${{ matrix.package }}'
          split-repository-organization: 'snlprjti'
          split-repository-name: '${{ matrix.package }}'
          user-name: "snlprjti"
          user-email: "snlprjpti@gmail.com"
          branch: "main"
