name: Split Test

on:
  push:
    branches:
      - master

    # see https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/10?u=tomasvotruba
    tags:
      - '*'

jobs:
  split_test:
    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v2

      -
        # run action.yaml in the root directory
        # see https://github.community/t/self-reference-an-action-for-testing/17891
        uses: "snlprjti/laramono@master"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          package_directory: 'packages/${{ matrix.package }}'
          repository_organization: 'snlprjti'
          repository_name: 'new_split'

          # change to use that should be signed under the split commit
          Username: 'snlprjti'
          user_email: 'sl.prjpti@gmail.com'